//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_Login.RegisterLoginServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegisterLoginServiceReference.Register_LoginWebServiceSoap")]
    public interface Register_LoginWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name CheckDatabaseConnectionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionResponse CheckDatabaseConnection(Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionResponse> CheckDatabaseConnectionAsync(Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsUserExists", ReplyAction="*")]
        Register_Login.RegisterLoginServiceReference.IsUserExistsResponse IsUserExists(Register_Login.RegisterLoginServiceReference.IsUserExistsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsUserExists", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.IsUserExistsResponse> IsUserExistsAsync(Register_Login.RegisterLoginServiceReference.IsUserExistsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        Register_Login.RegisterLoginServiceReference.RegisterUserResponse RegisterUser(Register_Login.RegisterLoginServiceReference.RegisterUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.RegisterUserResponse> RegisterUserAsync(Register_Login.RegisterLoginServiceReference.RegisterUserRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyLogin", ReplyAction="*")]
        Register_Login.RegisterLoginServiceReference.VerifyLoginResponse VerifyLogin(Register_Login.RegisterLoginServiceReference.VerifyLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.VerifyLoginResponse> VerifyLoginAsync(Register_Login.RegisterLoginServiceReference.VerifyLoginRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserId", ReplyAction="*")]
        Register_Login.RegisterLoginServiceReference.GetUserIdResponse GetUserId(Register_Login.RegisterLoginServiceReference.GetUserIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.GetUserIdResponse> GetUserIdAsync(Register_Login.RegisterLoginServiceReference.GetUserIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckDatabaseConnectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckDatabaseConnection", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequestBody Body;
        
        public CheckDatabaseConnectionRequest() {
        }
        
        public CheckDatabaseConnectionRequest(Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CheckDatabaseConnectionRequestBody {
        
        public CheckDatabaseConnectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckDatabaseConnectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckDatabaseConnectionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionResponseBody Body;
        
        public CheckDatabaseConnectionResponse() {
        }
        
        public CheckDatabaseConnectionResponse(Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckDatabaseConnectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckDatabaseConnectionResult;
        
        public CheckDatabaseConnectionResponseBody() {
        }
        
        public CheckDatabaseConnectionResponseBody(string CheckDatabaseConnectionResult) {
            this.CheckDatabaseConnectionResult = CheckDatabaseConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserExistsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserExists", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.RegisterLoginServiceReference.IsUserExistsRequestBody Body;
        
        public IsUserExistsRequest() {
        }
        
        public IsUserExistsRequest(Register_Login.RegisterLoginServiceReference.IsUserExistsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsUserExistsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userType;
        
        public IsUserExistsRequestBody() {
        }
        
        public IsUserExistsRequestBody(string email, string userType) {
            this.email = email;
            this.userType = userType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsUserExistsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUserExistsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.RegisterLoginServiceReference.IsUserExistsResponseBody Body;
        
        public IsUserExistsResponse() {
        }
        
        public IsUserExistsResponse(Register_Login.RegisterLoginServiceReference.IsUserExistsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsUserExistsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsUserExistsResult;
        
        public IsUserExistsResponseBody() {
        }
        
        public IsUserExistsResponseBody(bool IsUserExistsResult) {
            this.IsUserExistsResult = IsUserExistsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUser", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.RegisterLoginServiceReference.RegisterUserRequestBody Body;
        
        public RegisterUserRequest() {
        }
        
        public RegisterUserRequest(Register_Login.RegisterLoginServiceReference.RegisterUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string userType;
        
        public RegisterUserRequestBody() {
        }
        
        public RegisterUserRequestBody(string name, string email, string password, string userType) {
            this.name = name;
            this.email = email;
            this.password = password;
            this.userType = userType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.RegisterLoginServiceReference.RegisterUserResponseBody Body;
        
        public RegisterUserResponse() {
        }
        
        public RegisterUserResponse(Register_Login.RegisterLoginServiceReference.RegisterUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegisterUserResult;
        
        public RegisterUserResponseBody() {
        }
        
        public RegisterUserResponseBody(bool RegisterUserResult) {
            this.RegisterUserResult = RegisterUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyLogin", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.RegisterLoginServiceReference.VerifyLoginRequestBody Body;
        
        public VerifyLoginRequest() {
        }
        
        public VerifyLoginRequest(Register_Login.RegisterLoginServiceReference.VerifyLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string userType;
        
        public VerifyLoginRequestBody() {
        }
        
        public VerifyLoginRequestBody(string email, string password, string userType) {
            this.email = email;
            this.password = password;
            this.userType = userType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.RegisterLoginServiceReference.VerifyLoginResponseBody Body;
        
        public VerifyLoginResponse() {
        }
        
        public VerifyLoginResponse(Register_Login.RegisterLoginServiceReference.VerifyLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyLoginResult;
        
        public VerifyLoginResponseBody() {
        }
        
        public VerifyLoginResponseBody(bool VerifyLoginResult) {
            this.VerifyLoginResult = VerifyLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserId", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.RegisterLoginServiceReference.GetUserIdRequestBody Body;
        
        public GetUserIdRequest() {
        }
        
        public GetUserIdRequest(Register_Login.RegisterLoginServiceReference.GetUserIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userType;
        
        public GetUserIdRequestBody() {
        }
        
        public GetUserIdRequestBody(string email, string userType) {
            this.email = email;
            this.userType = userType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.RegisterLoginServiceReference.GetUserIdResponseBody Body;
        
        public GetUserIdResponse() {
        }
        
        public GetUserIdResponse(Register_Login.RegisterLoginServiceReference.GetUserIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetUserIdResult;
        
        public GetUserIdResponseBody() {
        }
        
        public GetUserIdResponseBody(int GetUserIdResult) {
            this.GetUserIdResult = GetUserIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Register_LoginWebServiceSoapChannel : Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Register_LoginWebServiceSoapClient : System.ServiceModel.ClientBase<Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap>, Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap {
        
        public Register_LoginWebServiceSoapClient() {
        }
        
        public Register_LoginWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Register_LoginWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Register_LoginWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Register_LoginWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionResponse Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap.CheckDatabaseConnection(Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequest request) {
            return base.Channel.CheckDatabaseConnection(request);
        }
        
        public string CheckDatabaseConnection() {
            Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequest inValue = new Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequest();
            inValue.Body = new Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequestBody();
            Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionResponse retVal = ((Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap)(this)).CheckDatabaseConnection(inValue);
            return retVal.Body.CheckDatabaseConnectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionResponse> Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap.CheckDatabaseConnectionAsync(Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequest request) {
            return base.Channel.CheckDatabaseConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionResponse> CheckDatabaseConnectionAsync() {
            Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequest inValue = new Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequest();
            inValue.Body = new Register_Login.RegisterLoginServiceReference.CheckDatabaseConnectionRequestBody();
            return ((Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap)(this)).CheckDatabaseConnectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.RegisterLoginServiceReference.IsUserExistsResponse Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap.IsUserExists(Register_Login.RegisterLoginServiceReference.IsUserExistsRequest request) {
            return base.Channel.IsUserExists(request);
        }
        
        public bool IsUserExists(string email, string userType) {
            Register_Login.RegisterLoginServiceReference.IsUserExistsRequest inValue = new Register_Login.RegisterLoginServiceReference.IsUserExistsRequest();
            inValue.Body = new Register_Login.RegisterLoginServiceReference.IsUserExistsRequestBody();
            inValue.Body.email = email;
            inValue.Body.userType = userType;
            Register_Login.RegisterLoginServiceReference.IsUserExistsResponse retVal = ((Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap)(this)).IsUserExists(inValue);
            return retVal.Body.IsUserExistsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.IsUserExistsResponse> Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap.IsUserExistsAsync(Register_Login.RegisterLoginServiceReference.IsUserExistsRequest request) {
            return base.Channel.IsUserExistsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.IsUserExistsResponse> IsUserExistsAsync(string email, string userType) {
            Register_Login.RegisterLoginServiceReference.IsUserExistsRequest inValue = new Register_Login.RegisterLoginServiceReference.IsUserExistsRequest();
            inValue.Body = new Register_Login.RegisterLoginServiceReference.IsUserExistsRequestBody();
            inValue.Body.email = email;
            inValue.Body.userType = userType;
            return ((Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap)(this)).IsUserExistsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.RegisterLoginServiceReference.RegisterUserResponse Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap.RegisterUser(Register_Login.RegisterLoginServiceReference.RegisterUserRequest request) {
            return base.Channel.RegisterUser(request);
        }
        
        public bool RegisterUser(string name, string email, string password, string userType) {
            Register_Login.RegisterLoginServiceReference.RegisterUserRequest inValue = new Register_Login.RegisterLoginServiceReference.RegisterUserRequest();
            inValue.Body = new Register_Login.RegisterLoginServiceReference.RegisterUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.userType = userType;
            Register_Login.RegisterLoginServiceReference.RegisterUserResponse retVal = ((Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap)(this)).RegisterUser(inValue);
            return retVal.Body.RegisterUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.RegisterUserResponse> Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap.RegisterUserAsync(Register_Login.RegisterLoginServiceReference.RegisterUserRequest request) {
            return base.Channel.RegisterUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.RegisterUserResponse> RegisterUserAsync(string name, string email, string password, string userType) {
            Register_Login.RegisterLoginServiceReference.RegisterUserRequest inValue = new Register_Login.RegisterLoginServiceReference.RegisterUserRequest();
            inValue.Body = new Register_Login.RegisterLoginServiceReference.RegisterUserRequestBody();
            inValue.Body.name = name;
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.userType = userType;
            return ((Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap)(this)).RegisterUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.RegisterLoginServiceReference.VerifyLoginResponse Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap.VerifyLogin(Register_Login.RegisterLoginServiceReference.VerifyLoginRequest request) {
            return base.Channel.VerifyLogin(request);
        }
        
        public bool VerifyLogin(string email, string password, string userType) {
            Register_Login.RegisterLoginServiceReference.VerifyLoginRequest inValue = new Register_Login.RegisterLoginServiceReference.VerifyLoginRequest();
            inValue.Body = new Register_Login.RegisterLoginServiceReference.VerifyLoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.userType = userType;
            Register_Login.RegisterLoginServiceReference.VerifyLoginResponse retVal = ((Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap)(this)).VerifyLogin(inValue);
            return retVal.Body.VerifyLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.VerifyLoginResponse> Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap.VerifyLoginAsync(Register_Login.RegisterLoginServiceReference.VerifyLoginRequest request) {
            return base.Channel.VerifyLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.VerifyLoginResponse> VerifyLoginAsync(string email, string password, string userType) {
            Register_Login.RegisterLoginServiceReference.VerifyLoginRequest inValue = new Register_Login.RegisterLoginServiceReference.VerifyLoginRequest();
            inValue.Body = new Register_Login.RegisterLoginServiceReference.VerifyLoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            inValue.Body.userType = userType;
            return ((Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap)(this)).VerifyLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.RegisterLoginServiceReference.GetUserIdResponse Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap.GetUserId(Register_Login.RegisterLoginServiceReference.GetUserIdRequest request) {
            return base.Channel.GetUserId(request);
        }
        
        public int GetUserId(string email, string userType) {
            Register_Login.RegisterLoginServiceReference.GetUserIdRequest inValue = new Register_Login.RegisterLoginServiceReference.GetUserIdRequest();
            inValue.Body = new Register_Login.RegisterLoginServiceReference.GetUserIdRequestBody();
            inValue.Body.email = email;
            inValue.Body.userType = userType;
            Register_Login.RegisterLoginServiceReference.GetUserIdResponse retVal = ((Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap)(this)).GetUserId(inValue);
            return retVal.Body.GetUserIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.GetUserIdResponse> Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap.GetUserIdAsync(Register_Login.RegisterLoginServiceReference.GetUserIdRequest request) {
            return base.Channel.GetUserIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.RegisterLoginServiceReference.GetUserIdResponse> GetUserIdAsync(string email, string userType) {
            Register_Login.RegisterLoginServiceReference.GetUserIdRequest inValue = new Register_Login.RegisterLoginServiceReference.GetUserIdRequest();
            inValue.Body = new Register_Login.RegisterLoginServiceReference.GetUserIdRequestBody();
            inValue.Body.email = email;
            inValue.Body.userType = userType;
            return ((Register_Login.RegisterLoginServiceReference.Register_LoginWebServiceSoap)(this)).GetUserIdAsync(inValue);
        }
    }
}
