//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_Login.SellerRequestsServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SellerRequestsServiceReference.SellerRequestsWebServiceSoap")]
    public interface SellerRequestsWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSellerRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddSellerRequest(string sellerId, string blanketId, string qty, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSellerRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddSellerRequestAsync(string sellerId, string blanketId, string qty, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerRequests", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSellerRequests(string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerRequests", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSellerRequestsAsync(string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerRequestsByStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSellerRequestsByStatus(string sellerId, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerRequestsByStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSellerRequestsByStatusAsync(string sellerId, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingRequestsBySellerList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPendingRequestsBySellerList(string sellerIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingRequestsBySellerList", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPendingRequestsBySellerListAsync(string sellerIdList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingRequestsBySellerListAndBlanket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPendingRequestsBySellerListAndBlanket(string sellerIdList, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingRequestsBySellerListAndBlanket", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPendingRequestsBySellerListAndBlanketAsync(string sellerIdList, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerRequestById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSellerRequestById(string requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerRequestById", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSellerRequestByIdAsync(string requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSellerRequestStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateSellerRequestStatus(string requestId, string status, System.DateTime updateDate, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSellerRequestStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateSellerRequestStatusAsync(string requestId, string status, System.DateTime updateDate, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSellerInventoryQty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateSellerInventoryQty(string sellerId, string blanketId, int qtyChange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSellerInventoryQty", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateSellerInventoryQtyAsync(string sellerId, string blanketId, int qtyChange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfirmedRequestsByDistributer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetConfirmedRequestsByDistributer(string distributerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfirmedRequestsByDistributer", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetConfirmedRequestsByDistributerAsync(string distributerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRejectedRequestsByDistributer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetRejectedRequestsByDistributer(string distributerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRejectedRequestsByDistributer", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetRejectedRequestsByDistributerAsync(string distributerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SellerRequestsWebServiceSoapChannel : Register_Login.SellerRequestsServiceReference.SellerRequestsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SellerRequestsWebServiceSoapClient : System.ServiceModel.ClientBase<Register_Login.SellerRequestsServiceReference.SellerRequestsWebServiceSoap>, Register_Login.SellerRequestsServiceReference.SellerRequestsWebServiceSoap {
        
        public SellerRequestsWebServiceSoapClient() {
        }
        
        public SellerRequestsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SellerRequestsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerRequestsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerRequestsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckDatabaseConnection() {
            return base.Channel.CheckDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync() {
            return base.Channel.CheckDatabaseConnectionAsync();
        }
        
        public string AddSellerRequest(string sellerId, string blanketId, string qty, string status) {
            return base.Channel.AddSellerRequest(sellerId, blanketId, qty, status);
        }
        
        public System.Threading.Tasks.Task<string> AddSellerRequestAsync(string sellerId, string blanketId, string qty, string status) {
            return base.Channel.AddSellerRequestAsync(sellerId, blanketId, qty, status);
        }
        
        public System.Data.DataSet GetSellerRequests(string sellerId) {
            return base.Channel.GetSellerRequests(sellerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSellerRequestsAsync(string sellerId) {
            return base.Channel.GetSellerRequestsAsync(sellerId);
        }
        
        public System.Data.DataSet GetSellerRequestsByStatus(string sellerId, string status) {
            return base.Channel.GetSellerRequestsByStatus(sellerId, status);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSellerRequestsByStatusAsync(string sellerId, string status) {
            return base.Channel.GetSellerRequestsByStatusAsync(sellerId, status);
        }
        
        public System.Data.DataSet GetPendingRequestsBySellerList(string sellerIdList) {
            return base.Channel.GetPendingRequestsBySellerList(sellerIdList);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPendingRequestsBySellerListAsync(string sellerIdList) {
            return base.Channel.GetPendingRequestsBySellerListAsync(sellerIdList);
        }
        
        public System.Data.DataSet GetPendingRequestsBySellerListAndBlanket(string sellerIdList, string blanketId) {
            return base.Channel.GetPendingRequestsBySellerListAndBlanket(sellerIdList, blanketId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPendingRequestsBySellerListAndBlanketAsync(string sellerIdList, string blanketId) {
            return base.Channel.GetPendingRequestsBySellerListAndBlanketAsync(sellerIdList, blanketId);
        }
        
        public System.Data.DataSet GetSellerRequestById(string requestId) {
            return base.Channel.GetSellerRequestById(requestId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSellerRequestByIdAsync(string requestId) {
            return base.Channel.GetSellerRequestByIdAsync(requestId);
        }
        
        public bool UpdateSellerRequestStatus(string requestId, string status, System.DateTime updateDate, string note) {
            return base.Channel.UpdateSellerRequestStatus(requestId, status, updateDate, note);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSellerRequestStatusAsync(string requestId, string status, System.DateTime updateDate, string note) {
            return base.Channel.UpdateSellerRequestStatusAsync(requestId, status, updateDate, note);
        }
        
        public bool UpdateSellerInventoryQty(string sellerId, string blanketId, int qtyChange) {
            return base.Channel.UpdateSellerInventoryQty(sellerId, blanketId, qtyChange);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSellerInventoryQtyAsync(string sellerId, string blanketId, int qtyChange) {
            return base.Channel.UpdateSellerInventoryQtyAsync(sellerId, blanketId, qtyChange);
        }
        
        public System.Data.DataSet GetConfirmedRequestsByDistributer(string distributerId) {
            return base.Channel.GetConfirmedRequestsByDistributer(distributerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetConfirmedRequestsByDistributerAsync(string distributerId) {
            return base.Channel.GetConfirmedRequestsByDistributerAsync(distributerId);
        }
        
        public System.Data.DataSet GetRejectedRequestsByDistributer(string distributerId) {
            return base.Channel.GetRejectedRequestsByDistributer(distributerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetRejectedRequestsByDistributerAsync(string distributerId) {
            return base.Channel.GetRejectedRequestsByDistributerAsync(distributerId);
        }
    }
}
