//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_Login.DistributerInventoryServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DistributerInventoryServiceReference.DistributerInventoryWebServiceSoap")]
    public interface DistributerInventoryWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDistributerInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddDistributerInventory(string inventoryId, string distributerId, string blanketId, int currentQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDistributerInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddDistributerInventoryAsync(string inventoryId, string distributerId, string blanketId, int currentQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDistributerInventory(string distributerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDistributerInventoryAsync(string distributerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributerInventoryQuantity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateDistributerInventoryQuantity(string inventoryId, int qtyChange, bool isAddition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributerInventoryQuantity", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateDistributerInventoryQuantityAsync(string inventoryId, int qtyChange, bool isAddition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerInventoryId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDistributerInventoryId(string distributerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerInventoryId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetDistributerInventoryIdAsync(string distributerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableQuantity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetAvailableQuantity(string distributerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableQuantity", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetAvailableQuantityAsync(string distributerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateInventory(string distributerId, string blanketId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateInventoryAsync(string distributerId, string blanketId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IncreaseInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IncreaseInventory(string distributerId, string blanketId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IncreaseInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IncreaseInventoryAsync(string distributerId, string blanketId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerInventoryByBlanket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDistributerInventoryByBlanket(string distributerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerInventoryByBlanket", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDistributerInventoryByBlanketAsync(string distributerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributerInventoryQty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateDistributerInventoryQty(string distributerId, string blanketId, int qtyChange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributerInventoryQty", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateDistributerInventoryQtyAsync(string distributerId, string blanketId, int qtyChange);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DistributerInventoryWebServiceSoapChannel : Register_Login.DistributerInventoryServiceReference.DistributerInventoryWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistributerInventoryWebServiceSoapClient : System.ServiceModel.ClientBase<Register_Login.DistributerInventoryServiceReference.DistributerInventoryWebServiceSoap>, Register_Login.DistributerInventoryServiceReference.DistributerInventoryWebServiceSoap {
        
        public DistributerInventoryWebServiceSoapClient() {
        }
        
        public DistributerInventoryWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistributerInventoryWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributerInventoryWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributerInventoryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckDatabaseConnection() {
            return base.Channel.CheckDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync() {
            return base.Channel.CheckDatabaseConnectionAsync();
        }
        
        public string AddDistributerInventory(string inventoryId, string distributerId, string blanketId, int currentQty) {
            return base.Channel.AddDistributerInventory(inventoryId, distributerId, blanketId, currentQty);
        }
        
        public System.Threading.Tasks.Task<string> AddDistributerInventoryAsync(string inventoryId, string distributerId, string blanketId, int currentQty) {
            return base.Channel.AddDistributerInventoryAsync(inventoryId, distributerId, blanketId, currentQty);
        }
        
        public System.Data.DataSet GetDistributerInventory(string distributerId) {
            return base.Channel.GetDistributerInventory(distributerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDistributerInventoryAsync(string distributerId) {
            return base.Channel.GetDistributerInventoryAsync(distributerId);
        }
        
        public string UpdateDistributerInventoryQuantity(string inventoryId, int qtyChange, bool isAddition) {
            return base.Channel.UpdateDistributerInventoryQuantity(inventoryId, qtyChange, isAddition);
        }
        
        public System.Threading.Tasks.Task<string> UpdateDistributerInventoryQuantityAsync(string inventoryId, int qtyChange, bool isAddition) {
            return base.Channel.UpdateDistributerInventoryQuantityAsync(inventoryId, qtyChange, isAddition);
        }
        
        public string GetDistributerInventoryId(string distributerId, string blanketId) {
            return base.Channel.GetDistributerInventoryId(distributerId, blanketId);
        }
        
        public System.Threading.Tasks.Task<string> GetDistributerInventoryIdAsync(string distributerId, string blanketId) {
            return base.Channel.GetDistributerInventoryIdAsync(distributerId, blanketId);
        }
        
        public int GetAvailableQuantity(string distributerId, string blanketId) {
            return base.Channel.GetAvailableQuantity(distributerId, blanketId);
        }
        
        public System.Threading.Tasks.Task<int> GetAvailableQuantityAsync(string distributerId, string blanketId) {
            return base.Channel.GetAvailableQuantityAsync(distributerId, blanketId);
        }
        
        public bool UpdateInventory(string distributerId, string blanketId, int quantity) {
            return base.Channel.UpdateInventory(distributerId, blanketId, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateInventoryAsync(string distributerId, string blanketId, int quantity) {
            return base.Channel.UpdateInventoryAsync(distributerId, blanketId, quantity);
        }
        
        public bool IncreaseInventory(string distributerId, string blanketId, int quantity) {
            return base.Channel.IncreaseInventory(distributerId, blanketId, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> IncreaseInventoryAsync(string distributerId, string blanketId, int quantity) {
            return base.Channel.IncreaseInventoryAsync(distributerId, blanketId, quantity);
        }
        
        public System.Data.DataSet GetDistributerInventoryByBlanket(string distributerId, string blanketId) {
            return base.Channel.GetDistributerInventoryByBlanket(distributerId, blanketId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDistributerInventoryByBlanketAsync(string distributerId, string blanketId) {
            return base.Channel.GetDistributerInventoryByBlanketAsync(distributerId, blanketId);
        }
        
        public bool UpdateDistributerInventoryQty(string distributerId, string blanketId, int qtyChange) {
            return base.Channel.UpdateDistributerInventoryQty(distributerId, blanketId, qtyChange);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDistributerInventoryQtyAsync(string distributerId, string blanketId, int qtyChange) {
            return base.Channel.UpdateDistributerInventoryQtyAsync(distributerId, blanketId, qtyChange);
        }
    }
}
