//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_Login.NewIDServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewIDServiceReference.GetNewIDWebServiceSoap")]
    public interface GetNewIDWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name CheckDatabaseConnectionResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        Register_Login.NewIDServiceReference.CheckDatabaseConnectionResponse CheckDatabaseConnection(Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.CheckDatabaseConnectionResponse> CheckDatabaseConnectionAsync(Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequest request);
        
        // CODEGEN: Generating message contract since element name autoMaterialIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoMaterialID", ReplyAction="*")]
        Register_Login.NewIDServiceReference.autoMaterialIDResponse autoMaterialID(Register_Login.NewIDServiceReference.autoMaterialIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoMaterialID", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoMaterialIDResponse> autoMaterialIDAsync(Register_Login.NewIDServiceReference.autoMaterialIDRequest request);
        
        // CODEGEN: Generating message contract since element name autoBlanketIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoBlanketID", ReplyAction="*")]
        Register_Login.NewIDServiceReference.autoBlanketIDResponse autoBlanketID(Register_Login.NewIDServiceReference.autoBlanketIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoBlanketID", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoBlanketIDResponse> autoBlanketIDAsync(Register_Login.NewIDServiceReference.autoBlanketIDRequest request);
        
        // CODEGEN: Generating message contract since element name autoOrderIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoOrderID", ReplyAction="*")]
        Register_Login.NewIDServiceReference.autoOrderIDResponse autoOrderID(Register_Login.NewIDServiceReference.autoOrderIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoOrderID", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoOrderIDResponse> autoOrderIDAsync(Register_Login.NewIDServiceReference.autoOrderIDRequest request);
        
        // CODEGEN: Generating message contract since element name autoSellerInventoryIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoSellerInventoryID", ReplyAction="*")]
        Register_Login.NewIDServiceReference.autoSellerInventoryIDResponse autoSellerInventoryID(Register_Login.NewIDServiceReference.autoSellerInventoryIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoSellerInventoryID", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoSellerInventoryIDResponse> autoSellerInventoryIDAsync(Register_Login.NewIDServiceReference.autoSellerInventoryIDRequest request);
        
        // CODEGEN: Generating message contract since element name autoDistributerInventoryIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoDistributerInventoryID", ReplyAction="*")]
        Register_Login.NewIDServiceReference.autoDistributerInventoryIDResponse autoDistributerInventoryID(Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoDistributerInventoryID", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoDistributerInventoryIDResponse> autoDistributerInventoryIDAsync(Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequest request);
        
        // CODEGEN: Generating message contract since element name autoManufacturerInventoryIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoManufacturerInventoryID", ReplyAction="*")]
        Register_Login.NewIDServiceReference.autoManufacturerInventoryIDResponse autoManufacturerInventoryID(Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/autoManufacturerInventoryID", ReplyAction="*")]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoManufacturerInventoryIDResponse> autoManufacturerInventoryIDAsync(Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckDatabaseConnectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckDatabaseConnection", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequestBody Body;
        
        public CheckDatabaseConnectionRequest() {
        }
        
        public CheckDatabaseConnectionRequest(Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CheckDatabaseConnectionRequestBody {
        
        public CheckDatabaseConnectionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckDatabaseConnectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckDatabaseConnectionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.CheckDatabaseConnectionResponseBody Body;
        
        public CheckDatabaseConnectionResponse() {
        }
        
        public CheckDatabaseConnectionResponse(Register_Login.NewIDServiceReference.CheckDatabaseConnectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckDatabaseConnectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CheckDatabaseConnectionResult;
        
        public CheckDatabaseConnectionResponseBody() {
        }
        
        public CheckDatabaseConnectionResponseBody(string CheckDatabaseConnectionResult) {
            this.CheckDatabaseConnectionResult = CheckDatabaseConnectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoMaterialIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoMaterialID", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoMaterialIDRequestBody Body;
        
        public autoMaterialIDRequest() {
        }
        
        public autoMaterialIDRequest(Register_Login.NewIDServiceReference.autoMaterialIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class autoMaterialIDRequestBody {
        
        public autoMaterialIDRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoMaterialIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoMaterialIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoMaterialIDResponseBody Body;
        
        public autoMaterialIDResponse() {
        }
        
        public autoMaterialIDResponse(Register_Login.NewIDServiceReference.autoMaterialIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class autoMaterialIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string autoMaterialIDResult;
        
        public autoMaterialIDResponseBody() {
        }
        
        public autoMaterialIDResponseBody(string autoMaterialIDResult) {
            this.autoMaterialIDResult = autoMaterialIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoBlanketIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoBlanketID", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoBlanketIDRequestBody Body;
        
        public autoBlanketIDRequest() {
        }
        
        public autoBlanketIDRequest(Register_Login.NewIDServiceReference.autoBlanketIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class autoBlanketIDRequestBody {
        
        public autoBlanketIDRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoBlanketIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoBlanketIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoBlanketIDResponseBody Body;
        
        public autoBlanketIDResponse() {
        }
        
        public autoBlanketIDResponse(Register_Login.NewIDServiceReference.autoBlanketIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class autoBlanketIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string autoBlanketIDResult;
        
        public autoBlanketIDResponseBody() {
        }
        
        public autoBlanketIDResponseBody(string autoBlanketIDResult) {
            this.autoBlanketIDResult = autoBlanketIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoOrderIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoOrderID", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoOrderIDRequestBody Body;
        
        public autoOrderIDRequest() {
        }
        
        public autoOrderIDRequest(Register_Login.NewIDServiceReference.autoOrderIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class autoOrderIDRequestBody {
        
        public autoOrderIDRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoOrderIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoOrderIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoOrderIDResponseBody Body;
        
        public autoOrderIDResponse() {
        }
        
        public autoOrderIDResponse(Register_Login.NewIDServiceReference.autoOrderIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class autoOrderIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string autoOrderIDResult;
        
        public autoOrderIDResponseBody() {
        }
        
        public autoOrderIDResponseBody(string autoOrderIDResult) {
            this.autoOrderIDResult = autoOrderIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoSellerInventoryIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoSellerInventoryID", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoSellerInventoryIDRequestBody Body;
        
        public autoSellerInventoryIDRequest() {
        }
        
        public autoSellerInventoryIDRequest(Register_Login.NewIDServiceReference.autoSellerInventoryIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class autoSellerInventoryIDRequestBody {
        
        public autoSellerInventoryIDRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoSellerInventoryIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoSellerInventoryIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoSellerInventoryIDResponseBody Body;
        
        public autoSellerInventoryIDResponse() {
        }
        
        public autoSellerInventoryIDResponse(Register_Login.NewIDServiceReference.autoSellerInventoryIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class autoSellerInventoryIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string autoSellerInventoryIDResult;
        
        public autoSellerInventoryIDResponseBody() {
        }
        
        public autoSellerInventoryIDResponseBody(string autoSellerInventoryIDResult) {
            this.autoSellerInventoryIDResult = autoSellerInventoryIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoDistributerInventoryIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoDistributerInventoryID", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequestBody Body;
        
        public autoDistributerInventoryIDRequest() {
        }
        
        public autoDistributerInventoryIDRequest(Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class autoDistributerInventoryIDRequestBody {
        
        public autoDistributerInventoryIDRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoDistributerInventoryIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoDistributerInventoryIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoDistributerInventoryIDResponseBody Body;
        
        public autoDistributerInventoryIDResponse() {
        }
        
        public autoDistributerInventoryIDResponse(Register_Login.NewIDServiceReference.autoDistributerInventoryIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class autoDistributerInventoryIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string autoDistributerInventoryIDResult;
        
        public autoDistributerInventoryIDResponseBody() {
        }
        
        public autoDistributerInventoryIDResponseBody(string autoDistributerInventoryIDResult) {
            this.autoDistributerInventoryIDResult = autoDistributerInventoryIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoManufacturerInventoryIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoManufacturerInventoryID", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequestBody Body;
        
        public autoManufacturerInventoryIDRequest() {
        }
        
        public autoManufacturerInventoryIDRequest(Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class autoManufacturerInventoryIDRequestBody {
        
        public autoManufacturerInventoryIDRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class autoManufacturerInventoryIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="autoManufacturerInventoryIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Register_Login.NewIDServiceReference.autoManufacturerInventoryIDResponseBody Body;
        
        public autoManufacturerInventoryIDResponse() {
        }
        
        public autoManufacturerInventoryIDResponse(Register_Login.NewIDServiceReference.autoManufacturerInventoryIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class autoManufacturerInventoryIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string autoManufacturerInventoryIDResult;
        
        public autoManufacturerInventoryIDResponseBody() {
        }
        
        public autoManufacturerInventoryIDResponseBody(string autoManufacturerInventoryIDResult) {
            this.autoManufacturerInventoryIDResult = autoManufacturerInventoryIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetNewIDWebServiceSoapChannel : Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetNewIDWebServiceSoapClient : System.ServiceModel.ClientBase<Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap>, Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap {
        
        public GetNewIDWebServiceSoapClient() {
        }
        
        public GetNewIDWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetNewIDWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetNewIDWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetNewIDWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.NewIDServiceReference.CheckDatabaseConnectionResponse Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.CheckDatabaseConnection(Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequest request) {
            return base.Channel.CheckDatabaseConnection(request);
        }
        
        public string CheckDatabaseConnection() {
            Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequest inValue = new Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequestBody();
            Register_Login.NewIDServiceReference.CheckDatabaseConnectionResponse retVal = ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).CheckDatabaseConnection(inValue);
            return retVal.Body.CheckDatabaseConnectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.CheckDatabaseConnectionResponse> Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.CheckDatabaseConnectionAsync(Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequest request) {
            return base.Channel.CheckDatabaseConnectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.CheckDatabaseConnectionResponse> CheckDatabaseConnectionAsync() {
            Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequest inValue = new Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.CheckDatabaseConnectionRequestBody();
            return ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).CheckDatabaseConnectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.NewIDServiceReference.autoMaterialIDResponse Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoMaterialID(Register_Login.NewIDServiceReference.autoMaterialIDRequest request) {
            return base.Channel.autoMaterialID(request);
        }
        
        public string autoMaterialID() {
            Register_Login.NewIDServiceReference.autoMaterialIDRequest inValue = new Register_Login.NewIDServiceReference.autoMaterialIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoMaterialIDRequestBody();
            Register_Login.NewIDServiceReference.autoMaterialIDResponse retVal = ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoMaterialID(inValue);
            return retVal.Body.autoMaterialIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoMaterialIDResponse> Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoMaterialIDAsync(Register_Login.NewIDServiceReference.autoMaterialIDRequest request) {
            return base.Channel.autoMaterialIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoMaterialIDResponse> autoMaterialIDAsync() {
            Register_Login.NewIDServiceReference.autoMaterialIDRequest inValue = new Register_Login.NewIDServiceReference.autoMaterialIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoMaterialIDRequestBody();
            return ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoMaterialIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.NewIDServiceReference.autoBlanketIDResponse Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoBlanketID(Register_Login.NewIDServiceReference.autoBlanketIDRequest request) {
            return base.Channel.autoBlanketID(request);
        }
        
        public string autoBlanketID() {
            Register_Login.NewIDServiceReference.autoBlanketIDRequest inValue = new Register_Login.NewIDServiceReference.autoBlanketIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoBlanketIDRequestBody();
            Register_Login.NewIDServiceReference.autoBlanketIDResponse retVal = ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoBlanketID(inValue);
            return retVal.Body.autoBlanketIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoBlanketIDResponse> Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoBlanketIDAsync(Register_Login.NewIDServiceReference.autoBlanketIDRequest request) {
            return base.Channel.autoBlanketIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoBlanketIDResponse> autoBlanketIDAsync() {
            Register_Login.NewIDServiceReference.autoBlanketIDRequest inValue = new Register_Login.NewIDServiceReference.autoBlanketIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoBlanketIDRequestBody();
            return ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoBlanketIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.NewIDServiceReference.autoOrderIDResponse Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoOrderID(Register_Login.NewIDServiceReference.autoOrderIDRequest request) {
            return base.Channel.autoOrderID(request);
        }
        
        public string autoOrderID() {
            Register_Login.NewIDServiceReference.autoOrderIDRequest inValue = new Register_Login.NewIDServiceReference.autoOrderIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoOrderIDRequestBody();
            Register_Login.NewIDServiceReference.autoOrderIDResponse retVal = ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoOrderID(inValue);
            return retVal.Body.autoOrderIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoOrderIDResponse> Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoOrderIDAsync(Register_Login.NewIDServiceReference.autoOrderIDRequest request) {
            return base.Channel.autoOrderIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoOrderIDResponse> autoOrderIDAsync() {
            Register_Login.NewIDServiceReference.autoOrderIDRequest inValue = new Register_Login.NewIDServiceReference.autoOrderIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoOrderIDRequestBody();
            return ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoOrderIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.NewIDServiceReference.autoSellerInventoryIDResponse Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoSellerInventoryID(Register_Login.NewIDServiceReference.autoSellerInventoryIDRequest request) {
            return base.Channel.autoSellerInventoryID(request);
        }
        
        public string autoSellerInventoryID() {
            Register_Login.NewIDServiceReference.autoSellerInventoryIDRequest inValue = new Register_Login.NewIDServiceReference.autoSellerInventoryIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoSellerInventoryIDRequestBody();
            Register_Login.NewIDServiceReference.autoSellerInventoryIDResponse retVal = ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoSellerInventoryID(inValue);
            return retVal.Body.autoSellerInventoryIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoSellerInventoryIDResponse> Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoSellerInventoryIDAsync(Register_Login.NewIDServiceReference.autoSellerInventoryIDRequest request) {
            return base.Channel.autoSellerInventoryIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoSellerInventoryIDResponse> autoSellerInventoryIDAsync() {
            Register_Login.NewIDServiceReference.autoSellerInventoryIDRequest inValue = new Register_Login.NewIDServiceReference.autoSellerInventoryIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoSellerInventoryIDRequestBody();
            return ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoSellerInventoryIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.NewIDServiceReference.autoDistributerInventoryIDResponse Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoDistributerInventoryID(Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequest request) {
            return base.Channel.autoDistributerInventoryID(request);
        }
        
        public string autoDistributerInventoryID() {
            Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequest inValue = new Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequestBody();
            Register_Login.NewIDServiceReference.autoDistributerInventoryIDResponse retVal = ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoDistributerInventoryID(inValue);
            return retVal.Body.autoDistributerInventoryIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoDistributerInventoryIDResponse> Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoDistributerInventoryIDAsync(Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequest request) {
            return base.Channel.autoDistributerInventoryIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoDistributerInventoryIDResponse> autoDistributerInventoryIDAsync() {
            Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequest inValue = new Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoDistributerInventoryIDRequestBody();
            return ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoDistributerInventoryIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Register_Login.NewIDServiceReference.autoManufacturerInventoryIDResponse Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoManufacturerInventoryID(Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequest request) {
            return base.Channel.autoManufacturerInventoryID(request);
        }
        
        public string autoManufacturerInventoryID() {
            Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequest inValue = new Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequestBody();
            Register_Login.NewIDServiceReference.autoManufacturerInventoryIDResponse retVal = ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoManufacturerInventoryID(inValue);
            return retVal.Body.autoManufacturerInventoryIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoManufacturerInventoryIDResponse> Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap.autoManufacturerInventoryIDAsync(Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequest request) {
            return base.Channel.autoManufacturerInventoryIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Register_Login.NewIDServiceReference.autoManufacturerInventoryIDResponse> autoManufacturerInventoryIDAsync() {
            Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequest inValue = new Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequest();
            inValue.Body = new Register_Login.NewIDServiceReference.autoManufacturerInventoryIDRequestBody();
            return ((Register_Login.NewIDServiceReference.GetNewIDWebServiceSoap)(this)).autoManufacturerInventoryIDAsync(inValue);
        }
    }
}
