//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_Login.BlanketServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BlanketServiceReference.BlanketWebServiceSoap")]
    public interface BlanketWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addBlanket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addBlanket(string BlanketID, string BlanketModel, string Material, string Capasity, string Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addBlanket", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addBlanketAsync(string BlanketID, string BlanketModel, string Material, string Capasity, string Price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBlanket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getBlanket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBlanket", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getBlanketAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchBlanketByname", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet searchBlanketByname(string BlanketModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchBlanketByname", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> searchBlanketBynameAsync(string BlanketModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchBlanketById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet searchBlanketById(string BlanketID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchBlanketById", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> searchBlanketByIdAsync(string BlanketID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllBlanketID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getAllBlanketID();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllBlanketID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAllBlanketIDAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBlanketModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getBlanketModel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBlanketModel", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getBlanketModelAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBlanketIDByModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getBlanketIDByModel(string BlanketModel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBlanketIDByModel", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getBlanketIDByModelAsync(string BlanketModel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BlanketWebServiceSoapChannel : Register_Login.BlanketServiceReference.BlanketWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BlanketWebServiceSoapClient : System.ServiceModel.ClientBase<Register_Login.BlanketServiceReference.BlanketWebServiceSoap>, Register_Login.BlanketServiceReference.BlanketWebServiceSoap {
        
        public BlanketWebServiceSoapClient() {
        }
        
        public BlanketWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BlanketWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlanketWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BlanketWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckDatabaseConnection() {
            return base.Channel.CheckDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync() {
            return base.Channel.CheckDatabaseConnectionAsync();
        }
        
        public string addBlanket(string BlanketID, string BlanketModel, string Material, string Capasity, string Price) {
            return base.Channel.addBlanket(BlanketID, BlanketModel, Material, Capasity, Price);
        }
        
        public System.Threading.Tasks.Task<string> addBlanketAsync(string BlanketID, string BlanketModel, string Material, string Capasity, string Price) {
            return base.Channel.addBlanketAsync(BlanketID, BlanketModel, Material, Capasity, Price);
        }
        
        public System.Data.DataSet getBlanket() {
            return base.Channel.getBlanket();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getBlanketAsync() {
            return base.Channel.getBlanketAsync();
        }
        
        public System.Data.DataSet searchBlanketByname(string BlanketModel) {
            return base.Channel.searchBlanketByname(BlanketModel);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> searchBlanketBynameAsync(string BlanketModel) {
            return base.Channel.searchBlanketBynameAsync(BlanketModel);
        }
        
        public System.Data.DataSet searchBlanketById(string BlanketID) {
            return base.Channel.searchBlanketById(BlanketID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> searchBlanketByIdAsync(string BlanketID) {
            return base.Channel.searchBlanketByIdAsync(BlanketID);
        }
        
        public System.Data.DataSet getAllBlanketID() {
            return base.Channel.getAllBlanketID();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAllBlanketIDAsync() {
            return base.Channel.getAllBlanketIDAsync();
        }
        
        public System.Data.DataSet getBlanketModel() {
            return base.Channel.getBlanketModel();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getBlanketModelAsync() {
            return base.Channel.getBlanketModelAsync();
        }
        
        public string getBlanketIDByModel(string BlanketModel) {
            return base.Channel.getBlanketIDByModel(BlanketModel);
        }
        
        public System.Threading.Tasks.Task<string> getBlanketIDByModelAsync(string BlanketModel) {
            return base.Channel.getBlanketIDByModelAsync(BlanketModel);
        }
    }
}
