//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_Login.SellerInventoryServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SellerInventoryServiceReference.SellerInventoryWebServiceSoap")]
    public interface SellerInventoryWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSellerInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddSellerInventory(string inventoryId, string sellerId, string blanketId, int currentQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSellerInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddSellerInventoryAsync(string inventoryId, string sellerId, string blanketId, int currentQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSellerInventory(string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSellerInventoryAsync(string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSellerInventoryQuantity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateSellerInventoryQuantity(string inventoryId, int qtyChange, bool isAddition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSellerInventoryQuantity", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateSellerInventoryQuantityAsync(string inventoryId, int qtyChange, bool isAddition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerInventoryId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSellerInventoryId(string sellerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerInventoryId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSellerInventoryIdAsync(string sellerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerCurrentQuantity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetSellerCurrentQuantity(string inventoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellerCurrentQuantity", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetSellerCurrentQuantityAsync(string inventoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInventoryBySellerAndModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetInventoryBySellerAndModel(string sellerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInventoryBySellerAndModel", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetInventoryBySellerAndModelAsync(string sellerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableQuantity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetAvailableQuantity(string sellerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableQuantity", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetAvailableQuantityAsync(string sellerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateInventory(string sellerId, string blanketId, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateInventoryAsync(string sellerId, string blanketId, int quantity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SellerInventoryWebServiceSoapChannel : Register_Login.SellerInventoryServiceReference.SellerInventoryWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SellerInventoryWebServiceSoapClient : System.ServiceModel.ClientBase<Register_Login.SellerInventoryServiceReference.SellerInventoryWebServiceSoap>, Register_Login.SellerInventoryServiceReference.SellerInventoryWebServiceSoap {
        
        public SellerInventoryWebServiceSoapClient() {
        }
        
        public SellerInventoryWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SellerInventoryWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerInventoryWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerInventoryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckDatabaseConnection() {
            return base.Channel.CheckDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync() {
            return base.Channel.CheckDatabaseConnectionAsync();
        }
        
        public string AddSellerInventory(string inventoryId, string sellerId, string blanketId, int currentQty) {
            return base.Channel.AddSellerInventory(inventoryId, sellerId, blanketId, currentQty);
        }
        
        public System.Threading.Tasks.Task<string> AddSellerInventoryAsync(string inventoryId, string sellerId, string blanketId, int currentQty) {
            return base.Channel.AddSellerInventoryAsync(inventoryId, sellerId, blanketId, currentQty);
        }
        
        public System.Data.DataSet GetSellerInventory(string sellerId) {
            return base.Channel.GetSellerInventory(sellerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSellerInventoryAsync(string sellerId) {
            return base.Channel.GetSellerInventoryAsync(sellerId);
        }
        
        public string UpdateSellerInventoryQuantity(string inventoryId, int qtyChange, bool isAddition) {
            return base.Channel.UpdateSellerInventoryQuantity(inventoryId, qtyChange, isAddition);
        }
        
        public System.Threading.Tasks.Task<string> UpdateSellerInventoryQuantityAsync(string inventoryId, int qtyChange, bool isAddition) {
            return base.Channel.UpdateSellerInventoryQuantityAsync(inventoryId, qtyChange, isAddition);
        }
        
        public string GetSellerInventoryId(string sellerId, string blanketId) {
            return base.Channel.GetSellerInventoryId(sellerId, blanketId);
        }
        
        public System.Threading.Tasks.Task<string> GetSellerInventoryIdAsync(string sellerId, string blanketId) {
            return base.Channel.GetSellerInventoryIdAsync(sellerId, blanketId);
        }
        
        public string GetSellerCurrentQuantity(string inventoryId) {
            return base.Channel.GetSellerCurrentQuantity(inventoryId);
        }
        
        public System.Threading.Tasks.Task<string> GetSellerCurrentQuantityAsync(string inventoryId) {
            return base.Channel.GetSellerCurrentQuantityAsync(inventoryId);
        }
        
        public System.Data.DataSet GetInventoryBySellerAndModel(string sellerId, string blanketId) {
            return base.Channel.GetInventoryBySellerAndModel(sellerId, blanketId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetInventoryBySellerAndModelAsync(string sellerId, string blanketId) {
            return base.Channel.GetInventoryBySellerAndModelAsync(sellerId, blanketId);
        }
        
        public int GetAvailableQuantity(string sellerId, string blanketId) {
            return base.Channel.GetAvailableQuantity(sellerId, blanketId);
        }
        
        public System.Threading.Tasks.Task<int> GetAvailableQuantityAsync(string sellerId, string blanketId) {
            return base.Channel.GetAvailableQuantityAsync(sellerId, blanketId);
        }
        
        public bool UpdateInventory(string sellerId, string blanketId, int quantity) {
            return base.Channel.UpdateInventory(sellerId, blanketId, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateInventoryAsync(string sellerId, string blanketId, int quantity) {
            return base.Channel.UpdateInventoryAsync(sellerId, blanketId, quantity);
        }
    }
}
