//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_Login.MaterialServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaterialServiceReference.MaterialWebServiceSoap")]
    public interface MaterialWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertMaterialInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string insertMaterialInfo(string MaterialID, string MaterialName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertMaterialInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> insertMaterialInfoAsync(string MaterialID, string MaterialName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchMaterial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet searchMaterial();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchMaterial", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> searchMaterialAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaterialName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getMaterialName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaterialName", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getMaterialNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaterialID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getMaterialID(string MaterialName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMaterialID", ReplyAction="*")]
        System.Threading.Tasks.Task<string> getMaterialIDAsync(string MaterialName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaterialWebServiceSoapChannel : Register_Login.MaterialServiceReference.MaterialWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialWebServiceSoapClient : System.ServiceModel.ClientBase<Register_Login.MaterialServiceReference.MaterialWebServiceSoap>, Register_Login.MaterialServiceReference.MaterialWebServiceSoap {
        
        public MaterialWebServiceSoapClient() {
        }
        
        public MaterialWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckDatabaseConnection() {
            return base.Channel.CheckDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync() {
            return base.Channel.CheckDatabaseConnectionAsync();
        }
        
        public string insertMaterialInfo(string MaterialID, string MaterialName) {
            return base.Channel.insertMaterialInfo(MaterialID, MaterialName);
        }
        
        public System.Threading.Tasks.Task<string> insertMaterialInfoAsync(string MaterialID, string MaterialName) {
            return base.Channel.insertMaterialInfoAsync(MaterialID, MaterialName);
        }
        
        public System.Data.DataSet searchMaterial() {
            return base.Channel.searchMaterial();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> searchMaterialAsync() {
            return base.Channel.searchMaterialAsync();
        }
        
        public System.Data.DataSet getMaterialName() {
            return base.Channel.getMaterialName();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getMaterialNameAsync() {
            return base.Channel.getMaterialNameAsync();
        }
        
        public string getMaterialID(string MaterialName) {
            return base.Channel.getMaterialID(MaterialName);
        }
        
        public System.Threading.Tasks.Task<string> getMaterialIDAsync(string MaterialName) {
            return base.Channel.getMaterialIDAsync(MaterialName);
        }
    }
}
