//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_Login.OrderServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderServiceReference.OrderWebServiceSoap")]
    public interface OrderWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string addOrder(string OrderID, string CustomerName, string SellerID, string BlanketID, string Qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<string> addOrderAsync(string OrderID, string CustomerName, string SellerID, string BlanketID, string Qty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersBySeller", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOrdersBySeller(string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrdersBySeller", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOrdersBySellerAsync(string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllOrders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllOrders", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ConfirmOrder(string orderId, string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConfirmOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ConfirmOrderAsync(string orderId, string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CanConfirmOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CanConfirmOrder(string orderId, string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CanConfirmOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CanConfirmOrderAsync(string orderId, string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOrderDetails(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetOrderDetailsAsync(string orderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingOrdersBySellerAndModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPendingOrdersBySellerAndModel(string sellerId, string modelSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingOrdersBySellerAndModel", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPendingOrdersBySellerAndModelAsync(string sellerId, string modelSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingOrdersBySellerAndBlanket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPendingOrdersBySellerAndBlanket(string sellerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingOrdersBySellerAndBlanket", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPendingOrdersBySellerAndBlanketAsync(string sellerId, string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchPendingOrdersByModel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SearchPendingOrdersByModel(string sellerId, string modelSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchPendingOrdersByModel", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchPendingOrdersByModelAsync(string sellerId, string modelSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApprovePendingOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ApprovePendingOrder(string orderId, string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApprovePendingOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ApprovePendingOrderAsync(string orderId, string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RejectPendingOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RejectPendingOrder(string orderId, string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RejectPendingOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RejectPendingOrderAsync(string orderId, string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfirmedOrdersBySeller", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetConfirmedOrdersBySeller(string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfirmedOrdersBySeller", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetConfirmedOrdersBySellerAsync(string sellerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderWebServiceSoapChannel : Register_Login.OrderServiceReference.OrderWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderWebServiceSoapClient : System.ServiceModel.ClientBase<Register_Login.OrderServiceReference.OrderWebServiceSoap>, Register_Login.OrderServiceReference.OrderWebServiceSoap {
        
        public OrderWebServiceSoapClient() {
        }
        
        public OrderWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckDatabaseConnection() {
            return base.Channel.CheckDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync() {
            return base.Channel.CheckDatabaseConnectionAsync();
        }
        
        public string addOrder(string OrderID, string CustomerName, string SellerID, string BlanketID, string Qty) {
            return base.Channel.addOrder(OrderID, CustomerName, SellerID, BlanketID, Qty);
        }
        
        public System.Threading.Tasks.Task<string> addOrderAsync(string OrderID, string CustomerName, string SellerID, string BlanketID, string Qty) {
            return base.Channel.addOrderAsync(OrderID, CustomerName, SellerID, BlanketID, Qty);
        }
        
        public System.Data.DataSet GetOrdersBySeller(string sellerId) {
            return base.Channel.GetOrdersBySeller(sellerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOrdersBySellerAsync(string sellerId) {
            return base.Channel.GetOrdersBySellerAsync(sellerId);
        }
        
        public System.Data.DataSet GetAllOrders() {
            return base.Channel.GetAllOrders();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllOrdersAsync() {
            return base.Channel.GetAllOrdersAsync();
        }
        
        public bool ConfirmOrder(string orderId, string sellerId) {
            return base.Channel.ConfirmOrder(orderId, sellerId);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmOrderAsync(string orderId, string sellerId) {
            return base.Channel.ConfirmOrderAsync(orderId, sellerId);
        }
        
        public bool CanConfirmOrder(string orderId, string sellerId) {
            return base.Channel.CanConfirmOrder(orderId, sellerId);
        }
        
        public System.Threading.Tasks.Task<bool> CanConfirmOrderAsync(string orderId, string sellerId) {
            return base.Channel.CanConfirmOrderAsync(orderId, sellerId);
        }
        
        public System.Data.DataSet GetOrderDetails(string orderId) {
            return base.Channel.GetOrderDetails(orderId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetOrderDetailsAsync(string orderId) {
            return base.Channel.GetOrderDetailsAsync(orderId);
        }
        
        public System.Data.DataSet GetPendingOrdersBySellerAndModel(string sellerId, string modelSearch) {
            return base.Channel.GetPendingOrdersBySellerAndModel(sellerId, modelSearch);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPendingOrdersBySellerAndModelAsync(string sellerId, string modelSearch) {
            return base.Channel.GetPendingOrdersBySellerAndModelAsync(sellerId, modelSearch);
        }
        
        public System.Data.DataSet GetPendingOrdersBySellerAndBlanket(string sellerId, string blanketId) {
            return base.Channel.GetPendingOrdersBySellerAndBlanket(sellerId, blanketId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPendingOrdersBySellerAndBlanketAsync(string sellerId, string blanketId) {
            return base.Channel.GetPendingOrdersBySellerAndBlanketAsync(sellerId, blanketId);
        }
        
        public System.Data.DataSet SearchPendingOrdersByModel(string sellerId, string modelSearch) {
            return base.Channel.SearchPendingOrdersByModel(sellerId, modelSearch);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchPendingOrdersByModelAsync(string sellerId, string modelSearch) {
            return base.Channel.SearchPendingOrdersByModelAsync(sellerId, modelSearch);
        }
        
        public bool ApprovePendingOrder(string orderId, string sellerId) {
            return base.Channel.ApprovePendingOrder(orderId, sellerId);
        }
        
        public System.Threading.Tasks.Task<bool> ApprovePendingOrderAsync(string orderId, string sellerId) {
            return base.Channel.ApprovePendingOrderAsync(orderId, sellerId);
        }
        
        public bool RejectPendingOrder(string orderId, string sellerId) {
            return base.Channel.RejectPendingOrder(orderId, sellerId);
        }
        
        public System.Threading.Tasks.Task<bool> RejectPendingOrderAsync(string orderId, string sellerId) {
            return base.Channel.RejectPendingOrderAsync(orderId, sellerId);
        }
        
        public System.Data.DataSet GetConfirmedOrdersBySeller(string sellerId) {
            return base.Channel.GetConfirmedOrdersBySeller(sellerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetConfirmedOrdersBySellerAsync(string sellerId) {
            return base.Channel.GetConfirmedOrdersBySellerAsync(sellerId);
        }
    }
}
