//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_Login.SellerManagementServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SellerManagementServiceReference.SellerManagementWebServiceSoap")]
    public interface SellerManagementWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAssignedSellers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAssignedSellers(string distributerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAssignedSellers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAssignedSellersAsync(string distributerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateSeller", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ValidateSeller(string sellerId, string sellerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateSeller", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ValidateSellerAsync(string sellerId, string sellerName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsSellerAssigned", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool IsSellerAssigned(string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsSellerAssigned", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsSellerAssignedAsync(string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AssignSeller", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AssignSeller(string distributerId, string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AssignSeller", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AssignSellerAsync(string distributerId, string sellerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveSellerAssignment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RemoveSellerAssignment(string sellerManagementId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveSellerAssignment", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RemoveSellerAssignmentAsync(string sellerManagementId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellersByDistributer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSellersByDistributer(string distributerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSellersByDistributer", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSellersByDistributerAsync(string distributerId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SellerManagementWebServiceSoapChannel : Register_Login.SellerManagementServiceReference.SellerManagementWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SellerManagementWebServiceSoapClient : System.ServiceModel.ClientBase<Register_Login.SellerManagementServiceReference.SellerManagementWebServiceSoap>, Register_Login.SellerManagementServiceReference.SellerManagementWebServiceSoap {
        
        public SellerManagementWebServiceSoapClient() {
        }
        
        public SellerManagementWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SellerManagementWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerManagementWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SellerManagementWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckDatabaseConnection() {
            return base.Channel.CheckDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync() {
            return base.Channel.CheckDatabaseConnectionAsync();
        }
        
        public System.Data.DataSet GetAssignedSellers(string distributerId) {
            return base.Channel.GetAssignedSellers(distributerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAssignedSellersAsync(string distributerId) {
            return base.Channel.GetAssignedSellersAsync(distributerId);
        }
        
        public bool ValidateSeller(string sellerId, string sellerName) {
            return base.Channel.ValidateSeller(sellerId, sellerName);
        }
        
        public System.Threading.Tasks.Task<bool> ValidateSellerAsync(string sellerId, string sellerName) {
            return base.Channel.ValidateSellerAsync(sellerId, sellerName);
        }
        
        public bool IsSellerAssigned(string sellerId) {
            return base.Channel.IsSellerAssigned(sellerId);
        }
        
        public System.Threading.Tasks.Task<bool> IsSellerAssignedAsync(string sellerId) {
            return base.Channel.IsSellerAssignedAsync(sellerId);
        }
        
        public string AssignSeller(string distributerId, string sellerId) {
            return base.Channel.AssignSeller(distributerId, sellerId);
        }
        
        public System.Threading.Tasks.Task<string> AssignSellerAsync(string distributerId, string sellerId) {
            return base.Channel.AssignSellerAsync(distributerId, sellerId);
        }
        
        public string RemoveSellerAssignment(string sellerManagementId) {
            return base.Channel.RemoveSellerAssignment(sellerManagementId);
        }
        
        public System.Threading.Tasks.Task<string> RemoveSellerAssignmentAsync(string sellerManagementId) {
            return base.Channel.RemoveSellerAssignmentAsync(sellerManagementId);
        }
        
        public System.Data.DataSet GetSellersByDistributer(string distributerId) {
            return base.Channel.GetSellersByDistributer(distributerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSellersByDistributerAsync(string distributerId) {
            return base.Channel.GetSellersByDistributerAsync(distributerId);
        }
    }
}
