//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_Login.DistributerRequestsServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DistributerRequestsServiceReference.DistributerRequestsWebServiceSoap")]
    public interface DistributerRequestsWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDistributerRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddDistributerRequest(string distributerId, string blanketId, int qty, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddDistributerRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddDistributerRequestAsync(string distributerId, string blanketId, int qty, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerRequests", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDistributerRequests(string distributerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerRequests", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDistributerRequestsAsync(string distributerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerRequestsByStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDistributerRequestsByStatus(string distributerId, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerRequestsByStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDistributerRequestsByStatusAsync(string distributerId, string status);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingDistributerRequests", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPendingDistributerRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingDistributerRequests", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPendingDistributerRequestsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingDistributerRequestsByBlanket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPendingDistributerRequestsByBlanket(string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPendingDistributerRequestsByBlanket", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPendingDistributerRequestsByBlanketAsync(string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerRequestById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDistributerRequestById(string requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDistributerRequestById", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDistributerRequestByIdAsync(string requestId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributerRequestStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateDistributerRequestStatus(string requestId, string status, System.DateTime updateDate, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributerRequestStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateDistributerRequestStatusAsync(string requestId, string status, System.DateTime updateDate, string note);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateManufacturerInventoryQty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateManufacturerInventoryQty(string blanketId, int qtyChange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateManufacturerInventoryQty", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateManufacturerInventoryQtyAsync(string blanketId, int qtyChange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributerInventoryQty", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateDistributerInventoryQty(string distributerId, string blanketId, int qtyChange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDistributerInventoryQty", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> UpdateDistributerInventoryQtyAsync(string distributerId, string blanketId, int qtyChange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfirmedRequestsByDistributer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetConfirmedRequestsByDistributer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConfirmedRequestsByDistributer", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetConfirmedRequestsByDistributerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRejectedRequests", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllRejectedRequests();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRejectedRequests", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllRejectedRequestsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DistributerRequestsWebServiceSoapChannel : Register_Login.DistributerRequestsServiceReference.DistributerRequestsWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DistributerRequestsWebServiceSoapClient : System.ServiceModel.ClientBase<Register_Login.DistributerRequestsServiceReference.DistributerRequestsWebServiceSoap>, Register_Login.DistributerRequestsServiceReference.DistributerRequestsWebServiceSoap {
        
        public DistributerRequestsWebServiceSoapClient() {
        }
        
        public DistributerRequestsWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DistributerRequestsWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributerRequestsWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DistributerRequestsWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckDatabaseConnection() {
            return base.Channel.CheckDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync() {
            return base.Channel.CheckDatabaseConnectionAsync();
        }
        
        public string AddDistributerRequest(string distributerId, string blanketId, int qty, string status) {
            return base.Channel.AddDistributerRequest(distributerId, blanketId, qty, status);
        }
        
        public System.Threading.Tasks.Task<string> AddDistributerRequestAsync(string distributerId, string blanketId, int qty, string status) {
            return base.Channel.AddDistributerRequestAsync(distributerId, blanketId, qty, status);
        }
        
        public System.Data.DataSet GetDistributerRequests(string distributerId) {
            return base.Channel.GetDistributerRequests(distributerId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDistributerRequestsAsync(string distributerId) {
            return base.Channel.GetDistributerRequestsAsync(distributerId);
        }
        
        public System.Data.DataSet GetDistributerRequestsByStatus(string distributerId, string status) {
            return base.Channel.GetDistributerRequestsByStatus(distributerId, status);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDistributerRequestsByStatusAsync(string distributerId, string status) {
            return base.Channel.GetDistributerRequestsByStatusAsync(distributerId, status);
        }
        
        public System.Data.DataSet GetPendingDistributerRequests() {
            return base.Channel.GetPendingDistributerRequests();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPendingDistributerRequestsAsync() {
            return base.Channel.GetPendingDistributerRequestsAsync();
        }
        
        public System.Data.DataSet GetPendingDistributerRequestsByBlanket(string blanketId) {
            return base.Channel.GetPendingDistributerRequestsByBlanket(blanketId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPendingDistributerRequestsByBlanketAsync(string blanketId) {
            return base.Channel.GetPendingDistributerRequestsByBlanketAsync(blanketId);
        }
        
        public System.Data.DataSet GetDistributerRequestById(string requestId) {
            return base.Channel.GetDistributerRequestById(requestId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDistributerRequestByIdAsync(string requestId) {
            return base.Channel.GetDistributerRequestByIdAsync(requestId);
        }
        
        public bool UpdateDistributerRequestStatus(string requestId, string status, System.DateTime updateDate, string note) {
            return base.Channel.UpdateDistributerRequestStatus(requestId, status, updateDate, note);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDistributerRequestStatusAsync(string requestId, string status, System.DateTime updateDate, string note) {
            return base.Channel.UpdateDistributerRequestStatusAsync(requestId, status, updateDate, note);
        }
        
        public bool UpdateManufacturerInventoryQty(string blanketId, int qtyChange) {
            return base.Channel.UpdateManufacturerInventoryQty(blanketId, qtyChange);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateManufacturerInventoryQtyAsync(string blanketId, int qtyChange) {
            return base.Channel.UpdateManufacturerInventoryQtyAsync(blanketId, qtyChange);
        }
        
        public bool UpdateDistributerInventoryQty(string distributerId, string blanketId, int qtyChange) {
            return base.Channel.UpdateDistributerInventoryQty(distributerId, blanketId, qtyChange);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDistributerInventoryQtyAsync(string distributerId, string blanketId, int qtyChange) {
            return base.Channel.UpdateDistributerInventoryQtyAsync(distributerId, blanketId, qtyChange);
        }
        
        public System.Data.DataSet GetConfirmedRequestsByDistributer() {
            return base.Channel.GetConfirmedRequestsByDistributer();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetConfirmedRequestsByDistributerAsync() {
            return base.Channel.GetConfirmedRequestsByDistributerAsync();
        }
        
        public System.Data.DataSet GetAllRejectedRequests() {
            return base.Channel.GetAllRejectedRequests();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllRejectedRequestsAsync() {
            return base.Channel.GetAllRejectedRequestsAsync();
        }
    }
}
