//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Register_Login.ManufacturerInventoryServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ManufacturerInventoryServiceReference.ManufacturerInventoryWebServiceSoap")]
    public interface ManufacturerInventoryWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckDatabaseConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckDatabaseConnection", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddManufacturerInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AddManufacturerInventory(string inventoryId, string blanketId, int currentQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddManufacturerInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AddManufacturerInventoryAsync(string inventoryId, string blanketId, int currentQty);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManufacturerInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetManufacturerInventory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManufacturerInventory", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetManufacturerInventoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateManufacturerInventoryQuantity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateManufacturerInventoryQuantity(string inventoryId, int qtyChange, bool isAddition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateManufacturerInventoryQuantity", ReplyAction="*")]
        System.Threading.Tasks.Task<string> UpdateManufacturerInventoryQuantityAsync(string inventoryId, int qtyChange, bool isAddition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManufacturerInventoryId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetManufacturerInventoryId(string blanketId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManufacturerInventoryId", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetManufacturerInventoryIdAsync(string blanketId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ManufacturerInventoryWebServiceSoapChannel : Register_Login.ManufacturerInventoryServiceReference.ManufacturerInventoryWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ManufacturerInventoryWebServiceSoapClient : System.ServiceModel.ClientBase<Register_Login.ManufacturerInventoryServiceReference.ManufacturerInventoryWebServiceSoap>, Register_Login.ManufacturerInventoryServiceReference.ManufacturerInventoryWebServiceSoap {
        
        public ManufacturerInventoryWebServiceSoapClient() {
        }
        
        public ManufacturerInventoryWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManufacturerInventoryWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturerInventoryWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManufacturerInventoryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckDatabaseConnection() {
            return base.Channel.CheckDatabaseConnection();
        }
        
        public System.Threading.Tasks.Task<string> CheckDatabaseConnectionAsync() {
            return base.Channel.CheckDatabaseConnectionAsync();
        }
        
        public string AddManufacturerInventory(string inventoryId, string blanketId, int currentQty) {
            return base.Channel.AddManufacturerInventory(inventoryId, blanketId, currentQty);
        }
        
        public System.Threading.Tasks.Task<string> AddManufacturerInventoryAsync(string inventoryId, string blanketId, int currentQty) {
            return base.Channel.AddManufacturerInventoryAsync(inventoryId, blanketId, currentQty);
        }
        
        public System.Data.DataSet GetManufacturerInventory() {
            return base.Channel.GetManufacturerInventory();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetManufacturerInventoryAsync() {
            return base.Channel.GetManufacturerInventoryAsync();
        }
        
        public string UpdateManufacturerInventoryQuantity(string inventoryId, int qtyChange, bool isAddition) {
            return base.Channel.UpdateManufacturerInventoryQuantity(inventoryId, qtyChange, isAddition);
        }
        
        public System.Threading.Tasks.Task<string> UpdateManufacturerInventoryQuantityAsync(string inventoryId, int qtyChange, bool isAddition) {
            return base.Channel.UpdateManufacturerInventoryQuantityAsync(inventoryId, qtyChange, isAddition);
        }
        
        public string GetManufacturerInventoryId(string blanketId) {
            return base.Channel.GetManufacturerInventoryId(blanketId);
        }
        
        public System.Threading.Tasks.Task<string> GetManufacturerInventoryIdAsync(string blanketId) {
            return base.Channel.GetManufacturerInventoryIdAsync(blanketId);
        }
    }
}
